version: 3
services:
  node:
    image: flyxdocker/qr-generator:latest
    container_name: node
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 80:9000
